language: python
python:
- 3.6
- nightly
before_install:
- openssl aes-256-cbc -K $encrypted_604cc47e123f_key -iv $encrypted_604cc47e123f_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- pip install -r requirements.txt
before_script:
- cd soundhub
script:
- python manage.py test

